/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'vidhan';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CONST = 'assets/Const.jpg';
  static const String BG1 = 'assets/bg1.jpeg';
  static const String CONST2 = 'assets/const2.jpg';
  static const String CONSTITUTION = 'assets/constitution.png';
  static const String CROWD = 'assets/crowd.jpg';
  static const String DOWNLOAD = 'assets/download.jpeg';
  static const String IMG1 = 'assets/img1.jpeg';
  static const String IMG2 = 'assets/img2.jpg';
  static const String IMG3 = 'assets/img3.jpg';
  static const String PART_IV = 'assets/part_IV.jpg';
  static const String PROFILE_RICHARD = 'assets/profile_richard.png';
  static const String PROTEST = 'assets/protest.jpg';
  static const String TRIANGLES = 'assets/triangles.png';
}
